### ISSUE TITLE
您好，可以增加一个关于医疗方面的机器人吗？MeChat：中文心理健康支持对话大模型

### ISSUE THREAD

**Issue by qiuhuachuan** [HqWu-HITCS/Awesome-Chinese-LLM#10]
简介：MeChat：中文心理健康支持对话大模型。该项目开源的中文心理健康支持通用模型由 ChatGLM-6B LoRA 16-bit 指令微调得到。数据集通过调用gpt-3.5-turbo API扩展真实的心理互助 QA为多轮的心理健康支持多轮对话，提高了通用语言大模型在心理健康支持领域的表现，更加符合在长程多轮对话的应用场景。

**Comment by AiHubCN** [comment]
感谢提供新的模型信息，能否麻烦提供一下项目链接呢？我尝试找了下没找到相关信息

**Comment by qiuhuachuan** [comment]
paper title: SMILE: Single-turn to Multi-turn Inclusive Language Expansion via ChatGPT for Mental Health Support
paper link: https://arxiv.org/pdf/2305.00450.pdf
code repo: https://github.com/qiuhuachuan/smile
感谢！

**Comment by AiHubCN** [comment]
已经加了哈，再次感谢反馈
