### ISSUE TITLE
如何解决大语言模型中的"幻觉"问题？

### ISSUE THREAD

**Issue by bigtang5** [HqWu-HITCS/Awesome-Chinese-LLM#11]
检索到信息：
大语言模型可能会编造数据，产生"幻觉"，可以用小唐搜索引擎来给生成的数据加上引用，让用户可以追溯数据的来源和可信度；
小唐搜索引擎是字符级搜索引擎，具有毫秒级的文本片段检索能力，效果类似：perplexity.ai
还有其它解决方案吗？

**Comment by AiHubCN** [comment]
除了上边提到的引入搜索引擎结果外，也可以尝试引入外部高质量的知识库（例如特定领域的文档等），让LLM发挥其总结提炼能力而不是生成能力从而减少幻觉；此外，还可以通过精细化的prompt设计去优化该问题，例如可以让LLM在生成结果之前给出生成这些结果的依据，或者让LLM生成多次结果进行融合；还可以引入多个LLM，让部分LLM做生成，剩余LLM做幻觉的检测和修复，具体可以参考论文https://arxiv.org/pdf/2305.15852.pdf的做法。
