### ISSUE TITLE
中文心理健康支持多轮对话数据集

### ISSUE THREAD

**Issue by qiuhuachuan** [HqWu-HITCS/Awesome-Chinese-LLM#17]
您好，提供一个数据集哈

SmileConv
地址：https://github.com/qiuhuachuan/smile
数据集说明：数据集通过ChatGPT改写真实的心理互助 QA为多轮的心理健康支持多轮对话（single-turn to multi-turn inclusive language expansion via ChatGPT），该数据集含有56k个多轮对话，其对话主题、词汇和篇章语义更加丰富多样，更加符合在长程多轮对话的应用场景。

**Comment by AiHubCN** [comment]
感谢提供数据集，可以直接发起pr哈，发起pr的是辛苦按照当前的格式发起即可～
