### ISSUE TITLE
推荐一个教育类的大语言模型项目 EduChat

### ISSUE THREAD

**Issue by twang2218** [HqWu-HITCS/Awesome-Chinese-LLM#21]
https://github.com/icalk-nlp/EduChat
<img width="955" alt="截屏2023-07-03 下午9 24 31" src="https://github.com/HqWu-HITCS/Awesome-Chinese-LLM/assets/6299096/a73344bd-22f7-4727-a020-264769a76f06">

**Comment by AiHubCN** [comment]
感谢提供的项目信息，已经合并进去了哈
