### ISSUE TITLE
或许可以用mindmap来可视化一下大语言模型

### ISSUE THREAD

**Issue by twang2218** [HqWu-HITCS/Awesome-Chinese-LLM#22]
我在总结大语言模型的时候，针对三个领域画了三张脑图，正好看到你的项目，很不错，是不是可以把脑图融入进来？

<img width="2517" alt="法律类大模型的应用" src="https://github.com/HqWu-HITCS/Awesome-Chinese-LLM/assets/6299096/af7d2451-4f28-48a0-8fd1-d66f1511d39c">
<img width="2623" alt="金融类大模型的应用" src="https://github.com/HqWu-HITCS/Awesome-Chinese-LLM/assets/6299096/0a197908-1364-4eb7-9bb9-3d5991e4925b">
<img width="2602" alt="医学类大模型的应用" src="https://github.com/HqWu-HITCS/Awesome-Chinese-LLM/assets/6299096/c102e62e-d2c1-4a4d-9df7-3ccc57faf27b">

我这是用 xmind 导入整理好的 markdown 的文件做的。有没有什么想法融入到这个项目里来？我可以帮忙把这个图整理到项目里来。

**Comment by AiHubCN** [comment]
非常详细的脑图，很赞，如果您方便的话可以发一个PR，把相应领域的脑图放到具体的项目信息之前，图的原文件可以放在src目录下哈
