### ISSUE TITLE
添加一个大模型的训练和部署框架

### ISSUE THREAD

**Issue by Tongjilibo** [HqWu-HITCS/Awesome-Chinese-LLM#29]
https://github.com/Tongjilibo/bert4torch

起源于苏神的bert4keras改torch版，目前在大模型上，已经包含了目前主要的开源大模型，llama系列，chatglm，bloom系列等等，代码简洁阅读性高，希望收纳

**Comment by AiHubCN** [comment]
感谢提供信息，已收纳
