### ISSUE TITLE
能否考虑加入各模型的推理和微调的硬件需求

### ISSUE THREAD

**Issue by LivingXu** [HqWu-HITCS/Awesome-Chinese-LLM#30]
这个仓库做了非常有价值的工作，十分受用。请问是否可以添加各模型推理和微调的硬件需求，以便于评估当前的硬件条件下能使用哪些模型。

**Comment by AiHubCN** [comment]
感谢提出的建议，模型推理和微调的硬件需求与具体的应用方式相关，对于特定的开源模型，是否量化，用不同的方式微调，不同的超参数等，都有着不同的硬件需求，因此较难在特定的开源项目下罗列出来具体的硬件；个人建议综合考虑模型参数规模（如7B or 33B，至于是baichuan-7B还是Qwen-7B区别可能不是那么大）和所需要的推理或微调方式出发整体考虑硬件需求。
