### ISSUE TITLE
CareLlama推荐

### ISSUE THREAD

**Issue by WangRongsheng** [HqWu-HITCS/Awesome-Chinese-LLM#32]
- https://github.com/WangRongsheng/CareLlama
- CareLlama (关怀羊驼)是一个医疗大语言模型，同时它集合了数十个公开可用的医疗微调数据集和开放可用的医疗大语言模型以促进医疗LLM快速发展。Medical LLM, Open Source Driven for a Healthy Future.

**Comment by AiHubCN** [comment]
感谢提供信息，已添加
