### ISSUE TITLE
有没有考虑提供中文 LLM 性能评测排行

### ISSUE THREAD

**Issue by Droliven** [HqWu-HITCS/Awesome-Chinese-LLM#33]
非常不错的工作，有没有考虑提供中文 LLM 性能评测排行

**Comment by AiHubCN** [comment]
感谢关注本项目，本项目梳理了LLM评测基准，通过这些评测基准可以得到当前开源LLM的评测排行。此外各个开源模型本身也大都会公开其在评测基准的指标。因此本项目没有再做额外梳理。
