### ISSUE TITLE
开源中文农业大模型：后稷

### ISSUE THREAD

**Issue by zhiweihu1103** [HqWu-HITCS/Awesome-Chinese-LLM#47]
单位：山西大学与山西农业大学
农业大模型后稷（AgriMa）：https://github.com/zhiweihu1103/AgriMa
希望能够添加进去

**Comment by AiHubCN** [comment]
感谢提供信息，欢迎参考当前格式直接提交pull request哈

**Comment by zhiweihu1103** [comment]
不好意思，我在仓库中没找到农业分支？

**Comment by AiHubCN** [comment]
可以在2.1后边新增一个农业的子项哈，具体格式参考已有的即可

**Comment by zhiweihu1103** [comment]
已添加，望审核
