### ISSUE TITLE
where is qwen2

### ISSUE THREAD

**Issue by StarLightInfinite** [HqWu-HITCS/Awesome-Chinese-LLM#68]
有点疑惑，qwen2怎么没上榜？

**Comment by Kennytian** [comment]
> 有点疑惑，qwen2怎么没上榜？

欢迎你补充进来

**Comment by goodturing** [comment]
unsubscribe



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 24, 2024 14:40 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [HqWu-HITCS/Awesome-Chinese-LLM] where is qwen2 (Issue #68)




  
有点疑惑，qwen2怎么没上榜？
  
欢迎你补充进来
